batch_size: 8
iters: 255000

train_dataset:
  type: MattingDataset
  dataset_root: /home/azureuser/bgrem_duts_plus_unsp_product_kgecomm_modnet
  train_file: train.txt
  transforms:
    - type: LoadImages
    - type: LimitLong
      min_long: 60
      max_long: 560
    - type: RandomCrop
      crop_size: [[512, 512]]
    - type: RandomDistort
    - type: RandomBlur
    - type: RandomHorizontalFlip
    - type: Normalize
    - type: Padding
      target_size: [512, 512]
      im_padding_value: [0, 0, 0]
  mode: train

val_dataset:
  type: MattingDataset
  dataset_root: /home/azureuser/bgrem_duts_plus_unsp_product_kgecomm_modnet
  val_file: val.txt
  transforms:
    - type: LoadImages
    - type: Normalize
    - type: LimitLong
      min_long: 60
      max_long: 512
    - type: Padding
      target_size: [512,512]
      im_padding_value: [0, 0, 0]
  mode: val
  get_trimap: False

model:
  type: MODNet
  backbone:
    type: MobileNetV2
    pretrained: https://hs-ml-models.sgp1.cdn.digitaloceanspaces.com/trained_models/bg_rem/PaddleSeg/model.pdparams
  pretrained: Null

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  warmup_iters: 25500
  warmup_start_lr: 0.000001
  type: CosineAnnealingDecay
  learning_rate: 0.02
  T_max: 229500
